### ISSUE TITLE
Incorrect usage of testing framework

### ISSUE THREAD

**Issue by darylwright** [jonestristand/hledger-parser#4]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ * ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Tests in this project are written in such a way that is:

a) Difficult to read and maintain individual tests, and
b) Unable to report on the status of tests subsequent to those that fail.

This is because what are intended to be tests in this project are actually assertions, and what is being used as suites are actually individual tests. Example:

```typescript
/*
  'journal' should be the name of the file containing the suite of tests. Each one of the assertions below need to
  be handled by a single `test()` function, depending on how closely related they are.
*/
test('journal', (t) => {
  const result1 = RawToCookedVisitor.journal(
    parseLedgerToRaw(`1900/01/01 transaction\n`).rawJournal
  );
  // Each instance of t.is() is an assertion, not a test. The message field should be used to display the value that failed.
  t.is(result1.transactions.length, 1, 'should have 1 parsed transaction');
  t.is(result1.accounts.length, 0, 'should have 0 parsed account directives');
  t.is(result1.prices.length, 0, 'should have 0 parsed price directives');

  // Additional setup after a series of assertions is a sign that the test should be split up
  const result2 = RawToCookedVisitor.journal(
    parseLedgerToRaw(`account Account:Test\n`).rawJournal
  );
  t.is(result2.transactions.length, 0, 'should have 0 parsed transactions');
  t.is(result2.accounts.length, 1, 'should have 1 parsed account directive');
  t.is(result2.prices.length, 0, 'should have 0 parsed price directives');

  const result3 = RawToCookedVisitor.journal(
    parseLedgerToRaw(`P 1900/01/01 CAD $1.00\n`).rawJournal
  );
  t.is(result3.transactions.length, 0, 'should have 0 parsed transactions');
  t.is(result3.accounts.length, 0, 'should have 0 parsed account directives');
  t.is(result3.prices.length, 1, 'should have 1 parsed price directive');
});
```

This way of writing tests encourages the inclusion of unrelated tests in the same file. This makes taking advantage of functions like `test.before()`, `test.beforeAll()`, `test.after()`, and `test.afterAll()` difficult, as you would have monolithic setup and teardown implemented to handle the various requirements of the different tests that are functioning as suites.

The way tests are currently written, it would be beneficial to put each one in an individual file. Then split out the assertions into individual `test()` functions, where the message of the assertion becomes the title of the test. Writing tests this way enables the developer to see if multiple tests fail at the same time.

Currently, with the assertions written as tests, when one fails, the whole 'suite' fails without running further tests. This makes it difficult to determine the true effect of a change as potential issues are hidden. Here's one way you can implement the above test:

```typescript
// journal.test.ts, contained in folder 'raw_to_cooked_visitor'
test.before(t => {
  t.context = {
    result1: RawToCookedVisitor.journal(
      parseLedgerToRaw(`1900/01/01 transaction\n`).rawJournal
    ),
    result2: RawToCookedVisitor.journal(
      parseLedgerToRaw(`account Account:Test\n`).rawJournal
    ),
    result3: RawToCookedVisitor.journal(
      parseLedgerToRaw(`P 1900/01/01 CAD $1.00\n`).rawJournal
    )
  };
});

test('should have 1 parsed transaction', (t) => {
  t.is(t.context.result1.transactions.length, 1, );
});

test('should have 0 parsed account directives', (t) => {
  t.is(t.context.result1.accounts.length, 0, );
});

test('should have 0 parsed price directives', (t) => {
  t.is(t.context.result1.prices.length, 0, );
});

test('should have 0 parsed transactions', (t) => {
  t.is(t.context.result2.transactions.length, 0, );
});

test('should have 1 parsed account directive', (t) => {
  t.is(t.context.result2.accounts.length, 1, );
});

test('should have 0 parsed price directives', (t) => {
  t.is(t.context.result2.prices.length, 0, );
});

test('should have 0 parsed transactions', (t) => {
  t.is(t.context.result3.transactions.length, 0, );
});

test('should have 0 parsed account directives', (t) => {
  t.is(t.context.result3.accounts.length, 0, );
});

test('should have 1 parsed price directive', (t) => {
  t.is(t.context.result3.prices.length, 1, );
});
```

Now we would be able to determine if multiple tests fail or not and get better insight as to the impact of changes. All tests ~~except for those in lexer.test.ts~~ need to be refactored similar to the above example so that we can start using the testing framework correctly, and also take advantage of additional testing features.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

[AVA documentation](https://github.com/avajs/ava/blob/e27183a9e8f6bb5ea12936f133796846af945154/docs/01-writing-tests.md)

**Comment by jonestristand** [comment]
You are absolutely right, and having to change this is one of the reasons I haven't made any changes to this project for the past year. The other way I was considering tests was to use one of the test suites of hledger/ledger journal files that are out there and making sure it can parse all of them...

**Comment by darylwright** [comment]
I figured as much why there hasn't been much activity. Once the tests are refactored, it will be much easier to implement the remainder of the hledger spec. I've been working on this for the past couple of weeks, expect a PR in the near future if you haven't done the same yourself.

Awesome work by the way! I use hledger for my family finances and was hoping for a project like this to appear.

**Comment by jonestristand** [comment]
That would be awesome! To be honest, a good PR/co-maintainer might be the impetus I need to put some work back into this :-)
