### ISSUE TITLE
Reorganization of lexer token and mode file structure to avoid circular imports

### ISSUE THREAD

**Issue by darylwright** [jonestristand/hledger-parser#7]
**I'm submitting a ...**
  [ ] bug report
  [ * ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

**Summary**

The current file structure for the lexer tokens and modes are prone to circular imports. When a circular import occurs, a module is referenced before its exports are defined, causing `undefined` to show up when not intended. The consequence of this issue is seen most easily during testing, when tests fail due to accesses on `undefined`.

Resolving this issue will make it easier to implement the remainder of the hledger spec, as we would not have to develop around the possibility of circular imports.

**Comment by jonestristand** [comment]
Can you give me some examples of where specifically you are getting circular dependencies? Will make it easier for me to restructure it in a useful way!

**Comment by darylwright** [comment]
I encountered this issue while trying to create new lexing modes and tokens. It's a bit difficult to describe, but I'm close to completing some work on this that I'll issue a PR for. You can take those changes or modify my approach if you had something different in mind.
